import { Schema, model } from "mongoose";
import { IProjects } from '../../types/projects';

export const ProjectsModelName = 'Projects';

const { Types } = Schema;

const ProjectsSchema = new Schema<IProjects>({
    M2Amount: { type: Types.String },
	adders: { type: Types.String },
	adders_description: { type: Types.String },
	cash_amount: { type: Types.String },
	companyOveride: { type: Types.Boolean },
	created: { type: Types.Date },
	customer_address: { type: Types.String },
	customer_address_2: { type: Types.String },
	customer_city: { type: Types.String },
	customer_email: { type: Types.String },
	customer_name: { type: Types.String },
	customer_phone: { type: Types.String },
	customer_signoff: { type: Types.String },
	customer_state: { type: Types.String },
	customer_zip: { type: Types.String },
	date_cancelled: { type: Types.Date },
	dealer_fee_percentage: { type: Types.String },
	employee_id: { type: Types.String },
	financing_rate: { type: Types.String },
	financing_term: { type: Types.String },
	funding_source: { type: Types.String },
	gross_account_value: { type: Types.String },
	homeowner_id: { type: Types.String },
	install_complete: { type: Types.String },
	install_partner: { type: Types.String },
	install_partner_id: { type: Types.String },
	kw: { type: Types.String },
	leadId: { type: Types.String },
	leadName: { type: Types.String },
	loan_amount: { type: Types.String },
	m1: { type: Types.Date },
	m2: { type: Types.Date },
	m1Paid: { type: Types.Boolean },
	m2Amount: { type: Types.String },
	m2Paid: { type: Types.Boolean },
	managerOverRide: { type: Types.String },
	modified: { type: Types.Date },
	overRidePaid: { type: Types.Boolean },
	product: { type: Types.String },
	proposal_id: { type: Types.String },
	prospect_id: { type: Types.String },
	repBonusAmount: { type: Types.String },
    repBonusPaid: { type: Types.Boolean },
    repKWM1: { type: Types.Boolean },
    repKWM1Paid: { type: Types.Boolean },
    repKWM2: { type: Types.Boolean },
    repKWM2Amount: { type: Types.String },
    repKWM2Paid: { type: Types.Boolean },
    rep_email: { type: Types.String },
    rep_name: { type: Types.String },
    return_sales_date: { type: Types.Date },
    scheduled_install: { type: Types.Date },
    setCommPaid: { type: Types.Boolean },
    setterBonusAmount: { type: Types.String },
    setterBonusPaid: { type: Types.Boolean },
    setterKWM1: { type: Types.Boolean },
    setterKWM2: { type: Types.Boolean },
    setter_id: { type: Types.String },
    createdAt: { type: Types.Date, default: Date.now() }
});

export const Projects = model<IProjects>(ProjectsModelName, ProjectsSchema);